/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppType: typeof import('./src/components/Chat/AppType.vue')['default']
    BackToBottom: typeof import('./src/components/Chat/BackToBottom.vue')['default']
    ChatItem: typeof import('./src/components/Chat/ChatItem.vue')['default']
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    CodeBase: typeof import('./src/components/CodeBase.vue')['default']
    DocumentHelper: typeof import('./src/components/DocumentHelper.vue')['default']
    GroupList: typeof import('./src/components/GroupList.vue')['default']
    Index: typeof import('./src/components/Chat/Index.vue')['default']
    LanguageSelector: typeof import('./src/components/LanguageSelector.vue')['default']
    LogoArea: typeof import('./src/components/LogoArea.vue')['default']
    MdContent: typeof import('./src/components/Common/MdContent.vue')['default']
    PersonalAccount: typeof import('./src/components/PersonalAccount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Sender: typeof import('./src/components/Chat/Sender.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SidebarToggle: typeof import('./src/components/SidebarToggle.vue')['default']
    TAside: typeof import('tdesign-vue-next')['Aside']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCheckTag: typeof import('tdesign-vue-next')['CheckTag']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    THeader: typeof import('tdesign-vue-next')['Header']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    TIcon: typeof import('tdesign-vue-next')['Icon']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopup: typeof import('tdesign-vue-next')['Popup']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSkeleton: typeof import('tdesign-vue-next')['Skeleton']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
