/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIWarning: typeof import('./src/components/AIWarning.vue')['default']
    ApplicationList: typeof import('./src/components/ApplicationList.vue')['default']
    AppType: typeof import('./src/components/Chat/AppType.vue')['default']
    BackToBottom: typeof import('./src/components/Chat/BackToBottom.vue')['default']
    ChatItem: typeof import('./src/components/Chat/ChatItem.vue')['default']
    ChatList: typeof import('./src/components/ChatList.vue')['default']
    CreateConversation: typeof import('./src/components/CreateConversation.vue')['default']
    CustomizedIcon: typeof import('./src/components/CustomizedIcon.vue')['default']
    FileList: typeof import('./src/components/Common/FileList.vue')['default']
    Index: typeof import('./src/components/Chat/Index.vue')['default']
    LogoArea: typeof import('./src/components/LogoArea.vue')['default']
    MdContent: typeof import('./src/components/Common/MdContent.vue')['default']
    OptionCard: typeof import('./src/components/Common/OptionCard.vue')['default']
    PersonalAccount: typeof import('./src/components/PersonalAccount.vue')['default']
    RecordIcon: typeof import('./src/components/Common/RecordIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Sender: typeof import('./src/components/Chat/Sender.vue')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SidebarToggle: typeof import('./src/components/SidebarToggle.vue')['default']
    TAlert: typeof import('tdesign-vue-next')['Alert']
    TAvatar: typeof import('tdesign-vue-next')['Avatar']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCheckbox: typeof import('tdesign-vue-next')['Checkbox']
    TCheckTag: typeof import('tdesign-vue-next')['CheckTag']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TContent: typeof import('tdesign-vue-next')['Content']
    TDialog: typeof import('tdesign-vue-next')['Dialog']
    TDivider: typeof import('tdesign-vue-next')['Divider']
    TDrawer: typeof import('tdesign-vue-next')['Drawer']
    TDropdown: typeof import('tdesign-vue-next')['Dropdown']
    TDropdownItem: typeof import('tdesign-vue-next')['DropdownItem']
    TDropdownMenu: typeof import('tdesign-vue-next')['DropdownMenu']
    TFooter: typeof import('tdesign-vue-next')['Footer']
    TForm: typeof import('tdesign-vue-next')['Form']
    TFormItem: typeof import('tdesign-vue-next')['FormItem']
    THeader: typeof import('tdesign-vue-next')['Header']
    TImage: typeof import('tdesign-vue-next')['Image']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLayout: typeof import('tdesign-vue-next')['Layout']
    TLink: typeof import('tdesign-vue-next')['Link']
    TLoading: typeof import('tdesign-vue-next')['Loading']
    TMessage: typeof import('tdesign-vue-next')['Message']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TSwitch: typeof import('tdesign-vue-next')['Switch']
    TTabPanel: typeof import('tdesign-vue-next')['TabPanel']
    TTabs: typeof import('tdesign-vue-next')['Tabs']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    TTooltip: typeof import('tdesign-vue-next')['Tooltip']
    TUpload: typeof import('tdesign-vue-next')['Upload']
  }
}
